#! /bin/bash

# autostart
killall -q sxhkd picom
# killall -q sxhkd
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
picom -b
# picom -fb --inactive-opacity 0.90  --active-opacity 0.95 &
$HOME/.fehbg
xrdb $HOME/.Xresources
$HOME/.config/bspwm/polybar.sh 

# wm settings
bspc monitor -d 1 2 3 4 5
bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
